### ISSUE TITLE
Pronunciation uses katakana; configurable to use hiragana?

### ISSUE THREAD

**Issue by benshine** [javdejong/nhk-pronunciation#2]
I'm using this plugin and I notice that the generated pronunciation seems to be in katakana, even for normal japanese words like 猫.
![screenshot 2016-02-07 08 13 14](https://cloud.githubusercontent.com/assets/21349/12873482/ae1d01b6-cd72-11e5-8426-f4d78a2a373e.png)

Is this something I can configure? I'd prefer hiragana, of course. 
I just looked at `nhk_pronunciation.csv` -- all of the information in there is in katakana. Is it possible to regenerate that file using hiragana? 
`猫    ネコ  <span class="overline">ネ</span>&#42780;コ`

**Comment by javdejong** [comment]
That is not something you can configurate at this moment. However, I can think of at least a few ways to accomplish what you want:
1. Generate a new nhk_pronunciation.csv, replacing every katakana in the third (and possibly second) field with its hiragana counterpart. A quick google search returned a few python packages that could make this almost trivial, e.g. jcconv.
2. Like 1, but instead use ACCDB_unicode.csv, and let the plugin regenerate nhk_pronunciation.csv upon startup. This happens when there is nonhk_pronunciation.csv file next to the python file (see build_database())
3. Amend the plugin to change the katakana to hiragana on the fly (look at the getPronunciations() function)

Note that you probably have to (1) make sure the old existing pickle file is deleted and (2) use the plugin's bulk-add feature to overwrite the existing entry in the "Pronunciation" field.

EDIT:
I have implemented the third option. The flag to choose between katakana and hiragana is now in the source file nhk_pronunciation.py, but when enough users (want to) use this feature I will consider moving it to a UI option.
