### ISSUE TITLE
How to interpret the data file?

### ISSUE THREAD

**Issue by seanblue** [javdejong/nhk-pronunciation#8]
First, sorry for creating an issue to ask this. As far as I could find, github doesn't have a messaging system.

1. Would you mind if someone grabbed your CSV file to use in another app?
2. I'm not sure how to interpret the pitch accent in the CSV file. Take for example these three words pronounced はし.

--------
箸 (pitch of [1]):
`74713,59776,J59776.wav,1,5109080010,ハシ,はし,箸,はし{箸},2,,,幼児がハシオ上手に使った,3,K59776.wav,ハシ,1,1,20`

橋 (pitch of [2]):
`74715,59778,J59778.wav,1,5109090010,ハシ,橋,橋,橋,2,,,三代の夫婦がハシオ渡り初めた,6,K59778.wav,ハシ,1,1,2`

端 (pitch of [0]):
`74716,59779,J59779.wav,1,5109100010,ハシ,端,端,端,2,,,道のハシワ崩れる心配があった,2,K59779.wav,ハシ,1,1,1`

--------
I'm not really sure how to interpret the 0s, 1s, and 2s in the last CSV value. Also, sometimes there are exactly the same number of digits as there are mora in the word (like 箸), and sometimes there is one less (like 橋 and 端).

It looks like heiban words always have all 1s, with one less digit than there is mora. Like 部室 (ぶしつ) has `11` in the last CSV value. But I'm having trouble figuring out the rest of the pattern. And are there any special rules to the pattern when there is a small っ in the word like 小学校 (しょうがっこう)?

Thanks!

**Comment by k3zi** [comment]
Old post but:

Basically the number 2 means that is where the accent drops (the peak). However leading `0`s are truncated from that string so you have to take that into account. I'll show analysis of some words:

合言葉 アイコトバ = 1200 
```
Has 5 characters while the accent has 4 characters, so we need to pad one 0 on the front:
01200 <= The 1 represents a raise in pitch from the base pitch.
The accent looks like LHHLL (L)
```

相まって アイマッテ = 20000
```
Has 5 characters while the accent has 5 characters so no need to pad.
20000 <= The peak is on the first mora. ッ counts as it's own mora
The accent looks like HLLLL (L)
```

青びょうたん アオビョータン = 112000
```
Has 7 characters (includes small characters) while the accent has 6, so we need to pad a 0 on the font:
0112000 = LHHHLLL (L) <= Notice that the accent actual drops after the ョ. 
Usually we would group ビョ but in this data it is showing the placement of the pitch drop relative to the characters.
```

The code in this repository basically:
1. Gets the number of characters in the word
2. Pads `0` onto the front of the accent so that it is the same length as the word
3. Uses the position of `2` as where the pitch drops OR
4. Uses the lack of `2` to know when something is flat

The way that the accent field is designed looks like you should be going from the back of the word:

あおみどろ アオミドロ = 1200
```
Forget the character count and just align it from the back (reverse loop, or flip string, etc...):
　１２００
アオミドロ <= Then we know the accent drops from ミ to ド
```
